dist: trusty
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - liblapack-dev
      - libgmp3-dev
      - libsuitesparse-dev
      - libeigen3-dev
before_script:
  - export CXX="g++-4.8" CC="gcc-4.8" FC="gfortran-4.8"
  - pushd ..
  - INSTALL_ROOT=$PWD/install
  - git clone https://github.com/Statoil/libecl.git
  - git clone https://github.com/OPM/opm-parser.git
  - mkdir libecl/build
  - pushd libecl/build
  - cmake -DBUILD_PYTHON=OFF -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT ..
  - make install
  - popd
  - mkdir opm-parser/build
  - pushd opm-parser/build
  - cmake -DCMAKE_MODULE_PATH=$INSTALL_ROOT/share/cmake/Modules -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON ..
  - make install
  - popd
  - popd
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_MODULE_PATH=$INSTALL_ROOT/share/cmake/Modules -Dopm-parser_DIR=$INSTALL_ROOT/lib/cmake/opm-parser ..
  - make
  - export PYTHONPATH=$PYTHONPATH:python
  - ctest --output-on-failure
