language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - liblapack-dev
      - libgmp3-dev
      - libsuitesparse-dev
      - libeigen3-dev
before_script:
  - export CXX="g++-4.8" CC="gcc-4.8" FC="gfortran-4.8"
  - SUNBEAM_ROOT=(`pwd`)
  - echo $SUNBEAM_ROOT
  - cd ..
  - SUN_ROOT=(`pwd`)
  - echo $SUN_ROOT
  - git clone https://github.com/Ensembles/ert.git
  - git clone https://github.com/OPM/opm-common.git
  - git clone https://github.com/OPM/opm-parser.git
  - cd ert
  - ERT_ROOT=(`pwd`)
  - echo $ERT_ROOT
  - mkdir build
  - cd build
  - cmake -DBUILD_PYTHON=OFF -DBUILD_TESTS=OFF ..
  - make
  - cd $SUN_ROOT/opm-common
  - OPM_COMMON_ROOT=(`pwd`)
  - echo $OPM_COMMON_ROOT
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd $SUN_ROOT/opm-parser
  - OPM_PARSER_ROOT=(`pwd`)
  - echo $OPM_PARSER_ROOT
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON ..
  - make
  - cd $SUNBEAM_ROOT
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_MODULE_PATH=$OPM_COMMON_ROOT/cmake/Modules ..
  - make
  - ctest --output-on-failure
