language: cpp
dist: trusty
sudo: false

compiler:
  - gcc

os:
  - linux

env:
  global:
    - PYENV_VERSION=2.7
    - INSTALL_ROOT=$HOME/install

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - gcc-4.8
      - g++-4.8
      - liblapack-dev


install:
  - pushd ..
  - git clone https://github.com/Statoil/libecl.git
  - git clone https://github.com/OPM/opm-parser.git
  - mkdir libecl/build
  - pushd libecl/build
  - cmake -DENABLE_PYTHON=OFF -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT ..
  - make install
  - popd
  - mkdir opm-parser/build
  - pushd opm-parser/build
  - git checkout release/2017.10/final
  - cmake -DCMAKE_PREFIX_PATH=$INSTALL_ROOT -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON ..
  - make install
  - popd
  - popd
  - pip install --user -r requirements.txt


script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_PREFIX_PATH=$INSTALL_ROOT -DUSE_RPATH=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_ROOT ..
  - make install
  - export PYTHONPATH=$PYTHONPATH:$INSTALL_ROOT/lib/python${PYENV_VERSION}/site-packages
  - ctest --output-on-failure
  - popd
